import { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[url('../assets/background.jpg')] h-[700px]">
        <div>{children}</div>
      </body>
    </html>
  );
}
